<?php require_once 'templates/layout/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>


<form method="POST" action="register">
  <div class="mb-3">
    <label for="usernameRegister" class="form-label">Nombre de usuario:</label>
    <input type="text" class="form-control" name="usernameRegister" id="usernameRegister" required>
  </div>
  <div class="mb-3">
    <label for="passwordRegister" class="form-label">Contraseña:</label>
    <input type="password" class="form-control" id="passwordRegister" name="passwordRegister" required>
  </div>
  <button type="submit" class="btn btn-primary">Registrese</button>
</form>

<?php require_once 'templates/layout/footer.phtml' ?>

