<h2 class="text-center mb-4">Ingresar Dueño</h2>

<div class="d-flex justify-content-center">
    <form action="addOwner" method="POST" id="formOwner" class="needs-validation p-4 bg-light border border-secondary rounded shadow w-50" novalidate>

        <div class="mb-3">
            <label for="nameOwnerAdd" class="form-label fw-bold">Nombre:</label>
            <input type="text" id="nameOwnerAdd" name="nameOwnerAdd" class="form-control" maxlength="50" pattern="[a-zA-Z\s]+" required>
        </div>

        <div class="mb-3">
            <label for="phoneOwnerAdd" class="form-label fw-bold">Teléfono:</label>
            <input type="text" id="phoneOwnerAdd" name="phoneOwnerAdd" class="form-control" maxlength="20" pattern="[a-zA-Z0-9\s]+" required>

        </div>

        <div class="mb-3">
            <label for="emailOwnerAdd" class="form-label fw-bold">Email:</label>
            <input type="email" id="emailOwnerAdd" name="emailOwnerAdd" class="form-control" maxlength="80" required>
        </div>

        <div class="d-flex justify-content-center">
            <button type="submit" class="btn btn-primary w-50">Guardar Dueño</button>
        </div>
    </form>
</div>