<tr>
    <td><?=htmlspecialchars($property->type) ?></td>
    <td><?=htmlspecialchars($property->zone) ?></td>
    <td><?=htmlspecialchars($property->price) ?></td>
    <td>
        <?php if (isset($properties)): ?>
            <?= substr(htmlspecialchars($property->description), 0, 20) ?>...
        <?php else : ?>
            <?= htmlspecialchars($property->description) ?>
        <?php endif ?>
    </td>
    <td><?= htmlspecialchars($property->mode) ?></td>
    <td><?= htmlspecialchars($property->status) ?></td>
    <td><?= htmlspecialchars($property->city) ?></td>
    <?php if (!isset($properties)): ?> <!-- porque quiero que aparezca cuando hay una sola prpiedad(solo para "ver mas") -->
        <td><?= htmlspecialchars($owner->name) ?></td>
    <?php endif ?>
    <?php if (isset($this->user)) : ?>

        <td><a class="btn btn-danger" href="deleteProperty/<?= $property->id_property ?>">Eliminar</a></td>
        <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalPropertyEdit<?= $property->id_property ?>" data-bs-whatever="@getbootstrap">Editar</button></td>
    <?php endif ?>
    <!-- si trae mas de una propiedad muestra ver mas, sino si trae solo una no pq ya esta en ver detalle  -->
    <?php if (isset($properties)): ?>
        <td><a class="btn btn-info text-light" href="property/<?= htmlspecialchars($property->id_property) ?>">Ver más</a></td>
    <?php endif ?>
</tr>

<div class="modal fade" id="modalPropertyEdit<?= $property->id_property ?>" tabindex="-1"
    aria-labelledby="modalPropertyEditLabel<?= $property->id_property ?>" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5"
                    id="modalPropertyEditLabel<?= $property->id_property ?>">Editar propiedad
                    <?= $property->id_property ?>:</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- updateProperty es una ruta del router -->
                <form action="updateProperty/<?= $property->id_property ?>" method="POST">
                    <input type="hidden" name="id_property" id="<?= $property->id_property ?>">
                    <div class="mb-3">
                        <label for="typePropertyEdit" class="col-form-label">Tipo:</label>
                        <select class="form-select" id="typePropertyEdit" name="typePropertyEdit" maxlength="20" pattern="[A-Za-z\s]+" required>
                            <option value="" selected disabled>Actualice el tipo de propiedad</option>
                            <option value="departamento">DEPARTAMENTO</option>
                            <option value="casa">CASA</option>
                            <option value="lote">LOTE</option>
                            <option value="quinta">QUINTA</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="zonePropertyEdit" class="col-form-label">Nueva zona :</label>
                        <input name="zonePropertyEdit" type="text" class="form-control"
                            id="zonePropertyEdit" maxlength="45" pattern="[A-Za-z0-9\s]+" required></input>
                    </div>
                    <div class="mb-3">
                        <label for="pricePropertyEdit" class="col-form-label">Nuevo precio:</label>
                        <input type="number" class="form-control" name="pricePropertyEdit"
                            id="pricePropertyEdit" required pattern="[0-9]{1,10}" min="0"
                            max="9999999999" maxlength="10"></input>
                    </div>
                    <div class="mb-3">
                        <label for="descriptionPropertyEdit" class="col-form-label">Nueva descripción
                            :</label>
                        <input name="descriptionPropertyEdit" type="text" class="form-control"
                            id="descriptionPropertyEdit" maxlength="500"
                            required></input>
                    </div>
                    <div class="mb-3">
                        <label for="modePropertyEdit" class="col-form-label">Nueva modalidad:</label>
                        <select class="form-select" id="modePropertyEdit" name="modePropertyEdit"
                            maxlength="20" pattern="[A-Za-z\s]+" required>
                            <option value="" selected disabled>Actualice la modalidad de la propiedad</option>
                            <option value="venta">VENTA</option>
                            <option value="alquiler">ALQUILER</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="statusPropertyEdit" class="col-form-label">Nuevo estado:</label>
                        <select class="form-select" id="statusPropertyEdit" name="statusPropertyEdit"
                            maxlength="20" pattern="[A-Za-z\s]+" required>
                            <option value="" selected disabled>Actualice el estado de la propiedad</option>
                            <option value="vendido">VENDIDO</option>
                            <option value="alquilado">ALQUILADO</option>
                            <option value="disponible">DISPONIBLE</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="cityPropertyEdit" class="col-form-label">Nueva ciudad :</label>
                        <input name="cityPropertyEdit" type="text" class="form-control"
                            id="cityPropertyEdit" maxlength="45" pattern="[A-Za-z0-9\s]+" required></input>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-bold" for="id_ownerPropertyEdit">Nuevo dueño:</label>
                        <select class="form-control" type="number" id="id_ownerPropertyEdit" name="id_ownerPropertyEdit" required>
                            <option value="" disabled selected>Cambie la categoría/dueño</option>
                            <?php foreach ($owners as $owner): ?>
                                <option value="<?= $owner->id_owner ?>"><?= $owner->name ?> </option>
                            <?php endforeach ?>
                        </select>
                    </div>

                    <input type="submit" class="btn btn-primary" value="Guarda Cambios"></input>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>