<?php require_once './templates/layout/header.phtml' ?>

<?php if ($this->user) : ?>
    <?php require_once './templates/form_add_owner.phtml' ?>
<?php endif ?>

<!--el controller me envia los duenios que el modelo pidio a la DB-->
<div class="container mt-5">
    <h2 class="text-center mb-4">Dueños</h2>
    <table class="table table-bordered table-striped">
        <thead class="table-header">
            <tr>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($owners as $owner): ?>
                <!-- require_once lo requiere una sola vez y genra una sola fila por eso se usa requiere -->
               <?php require './templates/item_list_owner_detail.phtml'?></a>
            <?php endforeach  ?>
        </tbody>
    </table>
</div>

<?php require_once './templates/layout/footer.phtml' ?>