<?php
        require_once './templates/layout/header.phtml';
        require_once './templates/form_add_owner.php';
        
?>
        <!--el controller me envia los duenios que el modelo pidio a la DB-->
        <div class="container mt-5">
            <h2 class="text-center mb-4">Dueños</h2>
            <table class="table table-bordered table-striped">
                <thead class="table-header">
                    <tr>
                        <th>Nombre</th>
                        <th>Teléfono</th>
                        <th>Email</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($owners as $owner): ?>
                        <tr>
                            <td><?php echo $owner->name ?> </td>
                            <td><?php echo $owner->phone ?> </td>
                            <td><?php echo $owner->email ?> </td>
                            <td><a class="btn btn-danger" href="deleteOwner/<?php echo $owner->id_owner ?>">Eliminar</a></td>
                            <td><button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modalOwnerEdit<?php echo $owner->id_owner ?>" data-bs-whatever="@getbootstrap">Editar</button></td>
                        </tr>

                        <!--  <div class="modal fade" id="modalOwnerEdit" tabindex="-1" aria-labelledby="modalOwnerEditLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="modalOwnerEditLabel">Editar dueño</h1>
                                        <h2 class=""> </h2>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form action="updateOwner" method="POST">
                                            <div class="mb-3">
                                                <label for="nameOwner" class="col-form-label">Nuevo nombre:</label>
                                                <input type="text" class="form-control" name="nameOwner" id="nameOwner">
                                            </div>
                                            <div class="mb-3">
                                                <label for="phoneOwner" class="col-form-label">Nuevo teléfono:</label>
                                                <input name="phoneOwner" type="tel" class="form-control" id="phoneOwner"></input>
                                            </div>
                                            <div class="mb-3">
                                                <label for="emailOwner" class="col-form-label">Nuevo email:</label>
                                                <input type="email" class="form-control" name="emailOwner" id="emailOwner"></input>
                                            </div>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary">Guarda Cambios</button>
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>
                        </div> -->

                        <div class="modal fade" id="modalOwnerEdit<?php echo $owner->id_owner ?>" tabindex="-1" aria-labelledby="modalOwnerEditLabel<?php echo $owner->id_owner ?>" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="modalOwnerEditLabel<?php echo $owner->id_owner ?>">Editar dueño <?php echo $owner->id_owner ?>:</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <!-- updateOwner es una ruta del router -->
                                        <form action="updateOwner/<?php echo $owner->id_owner?>" method="POST">
                                            <input type="hidden" name="id_owner" id="<?php echo $owner->id_owner ?>">
                                            <div class="mb-3">
                                                <label for="nameOwnerEdit" class="col-form-label">Nuevo nombre:</label>
                                                <input type="text" class="form-control" name="nameOwnerEdit" id="nameOwnerEdit">
                                            </div>
                                            <div class="mb-3">
                                                <label for="phoneOwnerEdit" class="col-form-label">Nuevo teléfono:</label>
                                                <input name="phoneOwnerEdit" type="tel" class="form-control" id="phoneOwnerEdit"></input>
                                            </div>
                                            <div class="mb-3">
                                                <label for="emailOwnerEdit" class="col-form-label">Nuevo email:</label>
                                                <input type="email" class="form-control" name="emailOwnerEdit" id="emailOwnerEdit"></input>
                                            </div>
                                            <input type="submit" class="btn btn-primary" value="Guarda Cambios"></input>
                                        </form>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                                    </div>
                                </div>
                            </div>

                        <?php endforeach  ?>
                </tbody>
            </table>
        </div>

    <?php require_once './templates/layout/footer.phtml'?>
    