<?php require_once './templates/layout/header.phtml' ?>

<?php if (isset($this->user)) : ?>
    <?php require_once './templates/form_add_owner.phtml' ?>
<?php endif ?>

<!--el controller me envia los duenios que el modelo pidio a la DB-->
<div class="container mt-5">
    <h2 class="text-center mb-4">Dueños</h2>
    <table class="table table-bordered table-striped">
        <thead class="table-header">
            <tr>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($owners as $owner): ?>
                <!-- require_once asegura que el archivo se incluya solo una vez en el ciclo de vida de la página, no es adecuado aquí. Si se usa require_once dentro del foreach, evita que la plantilla se cargue más de una vez, por lo que solo aparecerá un único dueño (la primera iteración).              
                  <?php require './templates/item_list_owner_detail.phtml'?>
            <?php endforeach;?>
        </tbody>
    </table>
</div>

<?php require_once './templates/layout/footer.phtml' ?>