<?php
require_once './templates/layout/header.phtml';
?>
<?php
require_once './templates/layout/header.phtml';
?>
<!--el controler me envia el duenio que el modelo pidio a la DB-->
<div class="container mt-5">
    <h2 class="text-center mb-4">Dueño</h2>
    <table class="table table-bordered table-striped">
        <thead class="table-header">
            <tr>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <!-- no es necesario hacer un foreach, trae un OBJETO  solo   -->
             <!-- la plantilla genera la tabla con el dueño y el modal de edicion de ese dueño  -->
            <?php require_once './templates/item_list_owner_detail.phtml' ?>
        </tbody>
    </table>
</div>



<?php
require_once './templates/layout/footer.phtml';
?><div class="container mt-5">
    <h2 class="text-center mb-4">Dueño</h2>
    <table class="table table-bordered table-striped">
        <thead class="table-header">
            <tr>
                <th>Nombre</th>
                <th>Teléfono</th>
                <th>Email</th>
            </tr>
        </thead>
        <tbody>
            <!-- no es necesario hacer un foreach, trae un OBJETO  solo   -->
             <!-- la plantilla genera la tabla con el dueño y el modal de edicion de ese dueño  -->
            <?php require_once './templates/item_list_owner_detail.phtml' ?>
        </tbody>
    </table>
</div>



<?php
require_once './templates/layout/footer.phtml';
?>