<?php require_once './templates/layout/header.phtml' ?>
<div class="container mt-5">
    <h2 class="text-center mb-4">Propiedades</h2>
    <table class="table table-bordered table-striped">
        <thead class="table-header">
            <tr>
                <th>Tipo</th>
                <th>Zona</th>
                <th>Precio</th>
                <th>Descripción</th>
                <th>Modalidad</th>
                <th>Estado</th>
                <th>Ciudad</th>
                <th>id_owner</th>
            </tr>
        </thead>
        <tbody>
            <?php require_once './templates/item_list_property_detail.phtml' ?>
        </tbody>
    </table>
</div>
<?php
require_once './templates/layout/footer.phtml' ?>