<!-- se van renderizando los siguientes templates antes que la tabla -:header,formualri para agregar propiedad-->
<?php require_once './templates/layout/header.phtml'; ?>
<!-- si existe un usuraio (si esta logeado),muesta el formulario para agregar una propiedad -->
<!-- isset($this->user)  verificar si la variable $this->user está definida. Esto evita el error de "variable indefinida" en caso de que $this->user no haya sido asignada aún. -->
<?php if (isset($this->user)) : ?>
    <?php require_once './templates/form_add_property.phtml'; ?>
<?php endif ?>

<?php require_once './templates/filter_properties.phtml'; ?>

<!--el controller me envia las propiedades que el modelo pidio a la DB-->
<div class="container mt-5">
    <h2 class="text-center mb-4">Propiedades</h2>
    <table class="table table-bordered table-striped">
        <thead class="table-header">
            <tr>
                <th>Tipo</th>
                <th>Zona</th>
                <th>Precio</th>
                <th>Descripción</th>
                <th>Modalidad</th>
                <th>Estado</th>
                <th>Ciudad</th>
                <th colspan="3" class="text-center">Acción</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($properties as $property): ?>
                <?php require './templates/item_list_property_detail.phtml' ?>
            <?php endforeach ?>
        </tbody>
    </table>
</div>

<?php require_once './templates/layout/footer.phtml'; ?>