</main>
<footer class="bg-dark text-white mt-5">
    <div class="container">
        <div class="row py-4">
            <!-- Sección Descripción -->
            <div class="col-lg-4 col-md-6 mb-4">
                <h5>Sobre nosotros</h5>
                <p>Somos una empresa comprometida con la excelencia en la venta y alquiler de propiedades. Contáctanos para más información.</p>
            </div>

            <!-- Sección Enlaces -->
            <div class="col-lg-4 col-md-6 mb-4">
                <h5>Enlaces</h5>
                <ul class="list-unstyled">
                    <li><a href="<?php echo BASE_URL ?>" class="text-white">Home</a></li>
                    <li><a href="<?php echo BASE_URL ?>getAllOwners" class="text-white">Dueños</a></li>
                </ul>
            </div>

            <!-- Sección Redes Sociales -->
            <div class="col-lg-4 col-md-12 mb-4">
                <h5>Síguenos</h5>
                
                <a href="https://www.instagram.com/inmobiliariagamalero/?hl=en" class="text-white">
                    <i class="bi bi-instagram"></i> Instagram
                </a>
                
                <a href="https://www.instagram.com/inmobiliariagamalero/?hl=en" class="text-white">
                    <i class="bi bi-instagram"></i> Facebook
                </a>
            </div>
        </div>

        <!-- Sección de Derechos Reservados -->
        <div class="text-center py-3 border-top border-secondary">
            <p class="mb-0">&copy; 2024 - Gamalero Inmobiliaria - Todos los derechos reservados.</p>
        </div>
    </div>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<!-- TODO: HACER VALIDACIONES DE FRONT  -->
</body>

</html>
