<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <base href="<?php echo BASE_URL ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inmobiliaria Gamalero</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="css/style.css">
    </head>

<body>

 <!-- render condicional: Si tenés un usuario en la session le imprimis el HTML que corresponde. Siempre, de todas maneras en el router se aplica el middleware de auth para los métodos que no querés que acceda nadie que no esté loguado -->
<!-- No alcanza con solo ocultar botones: se pone el verify -->

    <header>
        <nav class="navbar navbar-expand-lg bg-dark ">
            <div class="container">
                <a class="navbar-brand text-light" href="/<?php echo $BASE_URL?>">Inmobiliaria Gamalero</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" href="/<?php echo BASE_URL; ?>owners">Dueños</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link active text-light" aria-current="page" href="/<?php echo BASE_URL; ?>properties">Propiedades</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Propiedades
                            </a>
                            <ul class="dropdown-menu bg-dark">
                                <li><a class="dropdown-item text-light " href="#">Casa</a></li>
                                <li><a class="dropdown-item text-light" href="#">Departamento</a></li>
                                <li><a class="dropdown-item text-light" href="#">Quinta</a></li>
                                <li><a class="dropdown-item text-light" href="#">Lote</a></li>
                            </ul>
                        </li>
                    </ul>
                    <?php if ($this->user) :?>
                    <div class="w-50 d-flex justify-content-end">
                        <a class="btn btn-secondary text-light" href="logout">Cerrar sesión</a>
                    </div>
                    <?php else : ?>
                    <div class="w-50 d-flex justify-content-end">
                        <a class="btn btn-secondary text-light" href="showLogin">iniciar sessón</a>
                    </div>
                    <?php endif ?>

                </div>
            </div>
        </nav>
    </header>

    <main class="container">